<?php
/**
 * KeyGate v2.0 - Configuration File
 *
 * Generated by: Installation Wizard
 * Install Date: {INSTALL_DATE}
 * System Version: {OEM_VERSION}
 *
 * WARNING: This file contains sensitive database credentials
 * Ensure proper file permissions (600 or 644) and keep secure
 */

// Database Configuration
$db_config = [
    'host' => '{DB_HOST}',
    'dbname' => '{DB_NAME}',
    'username' => '{DB_USERNAME}',
    'password' => '{DB_PASSWORD}',
    'charset' => 'utf8mb4'
];

// Create PDO connection with error handling
try {
    $pdo = new PDO(
        "mysql:host={$db_config['host']};dbname={$db_config['dbname']};charset={$db_config['charset']}",
        $db_config['username'],
        $db_config['password'],
        [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
            PDO::ATTR_PERSISTENT => false,
            PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
        ]
    );
} catch (PDOException $e) {
    error_log("Database connection failed: " . $e->getMessage());
    http_response_code(500);
    die(json_encode([
        'success' => false,
        'error' => 'Database connection failed. Please contact administrator.'
    ]));
}

// Helper function to get configuration values from system_config table
function getConfig($key, $default = null) {
    global $pdo;
    try {
        $stmt = $pdo->prepare("SELECT config_value FROM `" . t('system_config') . "` WHERE config_key = ?");
        $stmt->execute([$key]);
        $result = $stmt->fetch();
        return $result ? $result['config_value'] : $default;
    } catch (PDOException $e) {
        error_log("Config retrieval failed for key '$key': " . $e->getMessage());
        return $default;
    }
}

// Helper function to set configuration values
function setConfig($key, $value, $description = '') {
    global $pdo;
    try {
        $stmt = $pdo->prepare("
            INSERT INTO `" . t('system_config') . "` (config_key, config_value, description)
            VALUES (?, ?, ?)
            ON DUPLICATE KEY UPDATE
                config_value = VALUES(config_value),
                description = IF(VALUES(description) != '', VALUES(description), description)
        ");
        $stmt->execute([$key, $value, $description]);
        return true;
    } catch (PDOException $e) {
        error_log("Config update failed for key '$key': " . $e->getMessage());
        return false;
    }
}

// Helper function to generate secure random token
function generateToken($length = 32) {
    return bin2hex(random_bytes($length));
}

// Helper function to generate secure session token (64 characters)
function generateSessionToken() {
    return bin2hex(random_bytes(32));
}

// Helper function to send JSON response
function jsonResponse($data, $status = 200) {
    http_response_code($status);
    header('Content-Type: application/json');
    header('X-Content-Type-Options: nosniff');
    header('X-Frame-Options: DENY');
    header('X-XSS-Protection: 1; mode=block');
    echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

// Helper function to validate technician credentials
function validateTechnician($technician_id, $password) {
    global $pdo;

    try {
        $stmt = $pdo->prepare("
            SELECT * FROM `" . t('technicians') . "`
            WHERE technician_id = ? AND is_active = 1
        ");
        $stmt->execute([$technician_id]);
        $technician = $stmt->fetch();

        if (!$technician) {
            return false;
        }

        // Check if account is locked
        if ($technician['locked_until'] && strtotime($technician['locked_until']) > time()) {
            return ['error' => 'account_locked', 'locked_until' => $technician['locked_until']];
        }

        // Verify password
        if (password_verify($password, $technician['password_hash'])) {
            // Reset failed attempts on successful login
            $stmt = $pdo->prepare("
                UPDATE `" . t('technicians') . "`
                SET failed_login_attempts = 0, locked_until = NULL, last_login = NOW()
                WHERE technician_id = ?
            ");
            $stmt->execute([$technician_id]);

            return $technician;
        }

        // Increment failed attempts
        $stmt = $pdo->prepare("
            UPDATE `" . t('technicians') . "`
            SET failed_login_attempts = failed_login_attempts + 1,
                locked_until = IF(failed_login_attempts + 1 >= 5, DATE_ADD(NOW(), INTERVAL 15 MINUTE), NULL)
            WHERE technician_id = ?
        ");
        $stmt->execute([$technician_id]);

        return false;

    } catch (PDOException $e) {
        error_log("Technician validation failed: " . $e->getMessage());
        return false;
    }
}

// Helper function to format product key for display (partial masking)
function formatProductKeySecure($key, $context = 'display') {
    if ($context === 'email') {
        // Show first 5 and last 5 characters for email
        return substr($key, 0, 5) . '-****-****-****-' . substr($key, -5);
    } else {
        // Show only first 5 for general display
        return substr($key, 0, 5) . '-****-****-****-*****';
    }
}

// System information
define('OEM_VERSION', '{OEM_VERSION}');
define('INSTALL_DATE', '{INSTALL_DATE}');
define('SYSTEM_NAME', 'KeyGate');

// Security settings
ini_set('session.cookie_httponly', 1);
ini_set('session.cookie_secure', 1);
ini_set('session.use_strict_mode', 1);
ini_set('session.cookie_samesite', 'Strict');

// Error reporting for production
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);
ini_set('error_log', __DIR__ . '/logs/php_errors.log');

// Timezone configuration
date_default_timezone_set('UTC');
