<?php
/**
 * KeyGate — License Validation & Enforcement
 *
 * Provides JWT-based license validation, tier checking, and feature gating.
 * The license system uses a simple JWT format signed with HMAC-SHA256.
 *
 * License tiers:
 *   community  — 1 technician, 50 keys, basic features (free)
 *   pro        — unlimited technicians & keys, all features
 *   enterprise — pro + multi-site, SSO, custom integrations
 */

// ── Tier Definitions ────────────────────────────────────────

define('LICENSE_TIERS', [
    'community' => [
        'label'            => 'Community',
        'max_technicians'  => 1,
        'max_keys'         => 50,
        'features'         => [
            'activation'   => true,
            'dashboard'    => true,
            'hardware'     => true,
            'backups'      => true,
            'integrations' => false,
            'compliance'   => false,
            'branding'     => false,
            'upgrade'      => false,
            'multi_admin'  => false,
        ],
    ],
    'pro' => [
        'label'            => 'Pro',
        'max_technicians'  => 9999,
        'max_keys'         => 999999,
        'features'         => [
            'activation'   => true,
            'dashboard'    => true,
            'hardware'     => true,
            'backups'      => true,
            'integrations' => true,
            'compliance'   => true,
            'branding'     => true,
            'upgrade'      => true,
            'multi_admin'  => true,
        ],
    ],
    'enterprise' => [
        'label'            => 'Enterprise',
        'max_technicians'  => 99999,
        'max_keys'         => 9999999,
        'features'         => [
            'activation'   => true,
            'dashboard'    => true,
            'hardware'     => true,
            'backups'      => true,
            'integrations' => true,
            'compliance'   => true,
            'branding'     => true,
            'upgrade'      => true,
            'multi_admin'  => true,
            'multi_site'   => true,
            'sso'          => true,
            'api_access'   => true,
        ],
    ],
]);

// ── Instance Fingerprint ────────────────────────────────────

/**
 * Generate a unique instance ID based on server characteristics.
 * This ID is tied to the installation and cannot be transferred.
 */
function generateInstanceId(PDO $pdo): string {
    // Combine: hostname + DB creation date + DB name + document root
    $hostname = gethostname() ?: 'unknown';
    $docRoot = $_SERVER['DOCUMENT_ROOT'] ?? '/var/www/html';

    // Get database creation timestamp (stable across restarts)
    try {
        $stmt = $pdo->query("SELECT MIN(created_at) AS first_record FROM admin_users");
        $row = $stmt->fetch();
        $dbSeed = $row['first_record'] ?? date('Y-m-d');
    } catch (Exception $e) {
        $dbSeed = date('Y-m-d');
    }

    $raw = implode('|', [$hostname, $dbSeed, $docRoot]);
    return hash('sha256', $raw);
}

/**
 * Get or create the instance ID (cached in system_config).
 */
function getInstanceId(PDO $pdo): string {
    $cached = getConfig('license_instance_id');
    if (!empty($cached)) {
        return $cached;
    }

    $instanceId = generateInstanceId($pdo);
    saveConfigBatch($pdo, ['license_instance_id' => $instanceId]);
    return $instanceId;
}

// ── JWT Helpers (HMAC-SHA256, no external deps) ─────────────

function base64UrlEncode(string $data): string {
    return rtrim(strtr(base64_encode($data), '+/', '-_'), '=');
}

function base64UrlDecode(string $data): string {
    return base64_decode(strtr($data, '-_', '+/'));
}

/**
 * Decode and verify a KeyGate license JWT.
 * Returns the payload array on success, or null on failure.
 *
 * @param string $jwt    The license JWT string
 * @param string $secret The HMAC secret (KeyGate public verification key)
 * @return array|null    Decoded payload or null
 */
function decodeLicenseJwt(string $jwt, string $secret = 'keygate-community-verification-key-2026'): ?array {
    $parts = explode('.', $jwt);
    if (count($parts) !== 3) {
        return null;
    }

    [$headerB64, $payloadB64, $signatureB64] = $parts;

    // Verify signature
    $signatureCheck = base64UrlEncode(
        hash_hmac('sha256', "$headerB64.$payloadB64", $secret, true)
    );

    if (!hash_equals($signatureCheck, $signatureB64)) {
        return null;
    }

    $payload = json_decode(base64UrlDecode($payloadB64), true);
    if (!is_array($payload)) {
        return null;
    }

    return $payload;
}

/**
 * Create a license JWT (for testing/development only — production keys
 * are generated by the KeyGate license server).
 */
function createLicenseJwt(array $payload, string $secret = 'keygate-community-verification-key-2026'): string {
    $header = base64UrlEncode(json_encode(['alg' => 'HS256', 'typ' => 'JWT']));
    $body = base64UrlEncode(json_encode($payload));
    $signature = base64UrlEncode(hash_hmac('sha256', "$header.$body", $secret, true));
    return "$header.$body.$signature";
}

// ── License Validation ──────────────────────────────────────

/**
 * Get the current license info from the database.
 * Returns the license row or null if no license is registered.
 */
function getCurrentLicense(PDO $pdo): ?array {
    try {
        $stmt = $pdo->query("SELECT * FROM license_info WHERE is_active = 1 ORDER BY id DESC LIMIT 1");
        return $stmt->fetch(PDO::FETCH_ASSOC) ?: null;
    } catch (Exception $e) {
        // Table may not exist yet (pre-migration)
        return null;
    }
}

/**
 * Get the effective license tier and limits.
 * Falls back to community tier if no valid license.
 */
function getEffectiveLicense(PDO $pdo): array {
    $license = getCurrentLicense($pdo);

    if ($license && $license['validation_status'] === 'valid') {
        $tier = $license['tier'] ?? 'community';
        $tierDef = LICENSE_TIERS[$tier] ?? LICENSE_TIERS['community'];

        return [
            'tier'             => $tier,
            'label'            => $tierDef['label'],
            'max_technicians'  => (int)$license['max_technicians'],
            'max_keys'         => (int)$license['max_keys'],
            'features'         => $tierDef['features'],
            'licensed_to'      => $license['licensed_to_email'] ?? '',
            'expires_at'       => $license['expires_at'],
            'is_registered'    => true,
            'instance_id'      => $license['instance_id'],
        ];
    }

    // Default community tier
    $communityDef = LICENSE_TIERS['community'];
    return [
        'tier'             => 'community',
        'label'            => 'Community',
        'max_technicians'  => $communityDef['max_technicians'],
        'max_keys'         => $communityDef['max_keys'],
        'features'         => $communityDef['features'],
        'licensed_to'      => '',
        'expires_at'       => null,
        'is_registered'    => ($license !== null),
        'instance_id'      => '',
    ];
}

/**
 * Register or update a license key.
 */
function registerLicense(PDO $pdo, string $licenseKey): array {
    $payload = decodeLicenseJwt($licenseKey);

    if (!$payload) {
        return ['success' => false, 'error' => 'Invalid license key — signature verification failed'];
    }

    // Validate required fields
    $required = ['tier', 'instance_id', 'iat', 'exp'];
    foreach ($required as $field) {
        if (empty($payload[$field])) {
            return ['success' => false, 'error' => "License missing required field: {$field}"];
        }
    }

    // Validate instance ID matches
    $instanceId = getInstanceId($pdo);
    if ($payload['instance_id'] !== $instanceId && $payload['instance_id'] !== '*') {
        return [
            'success' => false,
            'error' => 'License is for a different installation. Your instance ID: ' . substr($instanceId, 0, 12) . '...',
        ];
    }

    // Check expiration
    if ($payload['exp'] < time()) {
        return ['success' => false, 'error' => 'License has expired'];
    }

    $tier = $payload['tier'] ?? 'community';
    if (!isset(LICENSE_TIERS[$tier])) {
        return ['success' => false, 'error' => 'Unknown license tier: ' . $tier];
    }

    $tierDef = LICENSE_TIERS[$tier];

    // Deactivate any existing license
    $pdo->exec("UPDATE license_info SET is_active = 0");

    // Insert new license
    $stmt = $pdo->prepare("
        INSERT INTO license_info
            (license_key, instance_id, tier, licensed_to_email, licensed_to_name,
             max_technicians, max_keys, features,
             issued_at, expires_at, last_validated_at, validation_status, is_active)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, FROM_UNIXTIME(?), FROM_UNIXTIME(?), NOW(), 'valid', 1)
    ");
    $stmt->execute([
        $licenseKey,
        $instanceId,
        $tier,
        $payload['email'] ?? null,
        $payload['name'] ?? null,
        $payload['max_technicians'] ?? $tierDef['max_technicians'],
        $payload['max_keys'] ?? $tierDef['max_keys'],
        json_encode($tierDef['features']),
        $payload['iat'],
        $payload['exp'],
    ]);

    // Update system_config
    saveConfigBatch($pdo, ['license_tier' => $tier]);

    return [
        'success' => true,
        'tier'    => $tier,
        'label'   => $tierDef['label'],
        'message' => "License registered successfully — {$tierDef['label']} tier activated",
    ];
}

// ── Enforcement ─────────────────────────────────────────────

/**
 * Check if a specific feature is available in the current license tier.
 */
function isFeatureAvailable(PDO $pdo, string $feature): bool {
    $license = getEffectiveLicense($pdo);
    return !empty($license['features'][$feature]);
}

/**
 * Check if adding another technician would exceed the license limit.
 */
function canAddTechnician(PDO $pdo): array {
    $license = getEffectiveLicense($pdo);
    $stmt = $pdo->query("SELECT COUNT(*) FROM technicians WHERE status = 'active'");
    $currentCount = (int)$stmt->fetchColumn();

    if ($currentCount >= $license['max_technicians']) {
        return [
            'allowed' => false,
            'current' => $currentCount,
            'limit'   => $license['max_technicians'],
            'tier'    => $license['tier'],
            'message' => "Technician limit reached ({$currentCount}/{$license['max_technicians']}). Upgrade to Pro for unlimited technicians.",
        ];
    }

    return ['allowed' => true, 'current' => $currentCount, 'limit' => $license['max_technicians']];
}

/**
 * Check if adding more keys would exceed the license limit.
 */
function canAddKeys(PDO $pdo, int $count = 1): array {
    $license = getEffectiveLicense($pdo);
    $stmt = $pdo->query("SELECT COUNT(*) FROM oem_keys");
    $currentCount = (int)$stmt->fetchColumn();

    if (($currentCount + $count) > $license['max_keys']) {
        return [
            'allowed'   => false,
            'current'   => $currentCount,
            'adding'    => $count,
            'limit'     => $license['max_keys'],
            'tier'      => $license['tier'],
            'message'   => "Key limit reached ({$currentCount}/{$license['max_keys']}). Upgrade to Pro for unlimited keys.",
        ];
    }

    return ['allowed' => true, 'current' => $currentCount, 'limit' => $license['max_keys']];
}
